services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Instride\Bundle\OpenDxpDataDefinitionsBundle\Installer:
    public: true
    arguments:
      $bundle: '@=service("kernel").getBundle("OpenDxpDataDefinitionsBundle")'
