imports:
  - { resource: messenger.yml }

jms_serializer:
  metadata:
    directories:
      data-definitions:
        namespace_prefix: "DataDefinitionsBundle"
        path: "@DataDefinitionsBundle/Resources/config/serializer"

framework:
  http_client:
    enabled: true
