services:
    _defaults:
        autowire: true
        autoconfigure: true

    data_definitions.behat.filter.simple:
        class: Instride\Bundle\OpenDxpDataDefinitionsBundle\Behat\Service\Filter\SimpleFilter
        tags:
            - { name: data_definitions.filter, type: simple }
